### ISSUE TITLE
Inverse does not account for padding

### ISSUE THREAD

**Issue by gisilvs** [fversaci/WaveTF#10]
I would like to use the 2D Haar transform so that if the forward transformation introduced padding, the inverse transformation would then remove that padding, obtaining the initial input.

Happy to contribute if needed.

**Comment by fversaci** [comment]
In the 2D-Haar case, padding is added only when the number of rows or columns is odd and to obtain the original vector you just need to discard the last row/column.

However this information is not present in the transformed tensor, e.g., a tensor of shape [2,3,4] might derive from [4,6,1] (no padding) or from [3,5,1] (padding both in x and y), and therefore you cannot automatically recover the original tensor (unless, of course, you add the original tensor shape as an input to the process).
