### ISSUE TITLE
Inverse Wavelet Transform

### ISSUE THREAD

**Issue by oykueravci** [fversaci/WaveTF#13]
hey! Excellent project but I cannot design my model using inverse wavelet transform. I get this error that says : [[node model_4/inv_haar_wave_layer1d_6/Reshape (defined at kaggle/working/WaveTF/wavetf/_haar_mm.py:96) ]] [Op:__inference_train_function_19480]

Errors may have originated from an input operation.
Input Source operations connected to node model_4/inv_haar_wave_layer1d_6/Reshape:
 model_4/dropout_31/dropout/Mul_1 (defined at tmp/ipykernel_28/4029629701.py:5)

Function call stack:
train_function

Can you show me a basic model example that you used inverse wavelet transform that would be really helpful!

**Comment by fversaci** [comment]
Hi @oykueravci ,

I'll try to add a simple U-Net-like network to the examples soon :+1:

**Comment by fversaci** [comment]
I've added a `mini_unet.py` example, which makes use of the inverse transform.

**Comment by oykueravci** [comment]
Thank you so much! I didn't get a chance to respond yesterday. I was working on an autoencoder model so this example will be really helpful for my project! I wish you a really good day.

From: Francesco Versaci ***@***.***>
Date: Friday, 16 December 2022 13:47
To: fversaci/WaveTF ***@***.***>
Cc: Öykü ***@***.***>, Mention ***@***.***>
Subject: Re: [fversaci/WaveTF] Inverse Wavelet Transform (Issue #13)

I've added a mini_unet.py example, which makes use of the inverse transform.

**Comment by fversaci** [comment]
Same to you and good luck with your project!
