### ISSUE TITLE
Invalid value in tensor used for shape: -512

### ISSUE THREAD

**Issue by CTGUzhangguangyi** [fversaci/WaveTF#2]
tensorflow-gpu ==2.3
keras == 2.3

    wave_kern = 'db2'
    inputs = Input(shape)
    # x = wave(inputs)
    wave0 = inputs
    print(K.int_shape(inputs))
    wave1 = WaveTFFactory.build(wave_kern,dim=2)(wave0)

inputs is (None, 512, 512, 1)
error is Invalid value in tensor used for shape: -512

why did this mistake happen

**Comment by CTGUzhangguangyi** [comment]
I want try to run mini_cnn 

    ValueError: Invalid value in tensor used for shape: -512

The same thing happened

**Comment by fversaci** [comment]
I'll have a look and get back to you soon.

**Comment by fversaci** [comment]
I've pushed  a fix (commit 4b38e23) that should solve the issue.
Let me know if it now works for you. Thanks.

**Comment by CTGUzhangguangyi** [comment]
It's usable. Thanks
