### ISSUE TITLE
Other types of wavelets

### ISSUE THREAD

**Issue by pmdnhd** [fversaci/WaveTF#4]
Hi,

Do you think about implementing new wavelets such as db10, db15, ... ?
Or is there a way to implement them based on your code? 
I tried to do it on my own for db15 (only direct transform) but I got some shape issues. I believe it is due to the `daub_cols1` method and the padding which I am not sure to understand well. Do you have some insights for this?
Moreover, how will you handle the case when the input size is not a multiple of 20 or 30?

Thanks

**Comment by fversaci** [comment]
Hi, I'm currently working on another project, but I'll try and find some time in the next days either to draft a general 2D-Daubechies direct transform or at least give you some directions.

**Comment by pmdnhd** [comment]
Thanks, it would be for 1D direct transform instead of 2D if possible

**Comment by fversaci** [comment]
That's better, it's easier :)

**Comment by fversaci** [comment]
Hi, I've added a `general_kernel` branch with an implementation of a general 1D direct transform, which accepts as input the kernel to be used. It's not integrated with the rest of the interface yet, but you can see how to use in this [example](https://github.com/fversaci/WaveTF/blob/general_kernel/examples/gen_1d_wavelet.py).

Let me know if that works for you!

**Comment by pmdnhd** [comment]
Hi, thanks for your time!
I tried your snippet and it worked well. However, when trying to integrate the transform into a network, I got some trouble
```
import numpy as np
from wavetf._general_conv import KerWaveLayer1D
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Conv1D, Concatenate, Dense, Lambda, BatchNormalization, \
    GlobalAveragePooling1D, Activation
from tensorflow.keras.models import Model

ker_db15 = [
    [0.004538537361577376,     6.133359913303714e-08],
    [0.04674339489275062,      6.316882325879451e-07],
    [0.20602386398692688,      1.8112704079399406e-06],
    [0.4926317717079753,       -3.3629871817363823e-06],
    [0.6458131403572103,       -2.8133296266037558e-05],
    [0.33900253545462167,      -2.579269915531323e-05],
    [-0.19320413960907623,     0.00015589648992055726],
    [-0.28888259656686216,     0.00035956524436229364],
    [0.06528295284876569,      -0.0003734823541372647],
    [0.19014671400708816,      -0.0019433239803823459],
    [-0.0396661765557336,      -0.00024175649075894543],
    [-0.11112093603713753,     0.0064877345603061454],
    [0.033877143923563204,     0.005101000360422873],
    [0.054780550584559995,     -0.015083918027862582],
    [-0.02576700732836694,     -0.020810050169636805],
    [-0.020810050169636805,    0.02576700732836694],
    [0.015083918027862582,     0.054780550584559995],
    [0.005101000360422873,     -0.033877143923563204],
    [-0.0064877345603061454,   -0.11112093603713753],
    [-0.00024175649075894543,  0.0396661765557336],
    [0.0019433239803823459,    0.19014671400708816],
    [-0.0003734823541372647,   -0.06528295284876569],
    [-0.00035956524436229364,  -0.28888259656686216],
    [0.00015589648992055726,   0.19320413960907623],
    [2.579269915531323e-05,    0.33900253545462167],
    [-2.8133296266037558e-05,  -0.6458131403572103],
    [3.3629871817363823e-06,   0.4926317717079753],
    [1.8112704079399406e-06,   -0.20602386398692688],
    [-6.316882325879451e-07,   0.04674339489275062],
    [6.133359913303714e-08,    -0.004538537361577376],
]

ker_db15 = tf.convert_to_tensor(ker_db15, dtype=tf.float64)

db15 = KerWaveLayer1D(ker_db15)

def wavelet_cnn(input_shape, ks=3, baselev=4, wavelet=True,
                wave_kern='db2', convrep=4, num_classes=2):
    inputs = Input(input_shape[1:])
    chans = input_shape[2]  # number of channels, e.g., 3 if RGB
    bl = baselev

    # wavelet computation
    if (wavelet):
        wave0 = inputs
        wave1 = db15.call(wave0[:, :, :chans])
        wave2 = db15.call(wave1[:, :, :chans])
        wave3 = db15.call(wave2[:, :, :chans])
        wave4 = db15.call(wave3[:, :, :chans])
        waves = [wave1, wave2, wave3, wave4]
        for l in range(len(waves)):
            waves[l] = BatchNormalization()(waves[l])
    else:
        wave1 = wave2 = wave3 = wave4 = None

    kinit = 'glorot_normal'  # 'he_normal'

    def rep_conv(cnn, scale=1):
        for i in range(convrep):
            cnn = Conv1D(scale * bl, ks, activation='relu', padding='same',
                         kernel_initializer=kinit)(cnn)
        return cnn

    def pool_down(cnn, mul):
        cnn = Conv1D(mul * bl, ks, activation='relu', padding='same',
                     kernel_initializer=kinit, strides=2)(cnn)
        return (cnn)

    cnn = inputs
    cnn = rep_conv(cnn, 1)

    for l in range(len(waves)):
        cnn = pool_down(cnn, 2 ** (l + 1))
        cnn = rep_conv(cnn, 2 ** (l + 1))
        if (wavelet):
            cnn = Concatenate(axis=2)([cnn, waves[l]])

    # output
    cnn = Conv1D(2048, ks)(cnn)
    cnn = Activation('relu')(cnn)
    cnn = GlobalAveragePooling1D()(cnn)
    # outputs = Dense(num_classes, activation='softmax')(cnn)
    outputs = Dense(1, activation='sigmoid')(cnn)
    model = Model(inputs=inputs, outputs=outputs)

    return model

# Let's say we have only 20 samples divided into train/test sets. each sample is 1638 long
x_train = np.random.rand(10, 1638).astype(np.float64)
x_test = np.random.rand(10, 1638).astype(np.float64)
y_train = [0, 1, 0, 1, 0, 0, 1, 0, 1, 0]
y_test = [0, 1, 0, 1, 0, 0, 1, 0, 1, 0]

nb_epochs = 1
nb_classes = 2

batch_size = 32

y_train = np.array(y_train)
y_test = np.array(y_test)

x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

model = wavelet_cnn((batch_size, x_train.shape[1], 1), ks=3, baselev=2, wavelet=True, wave_kern='db2',
                    convrep=2, num_classes=nb_classes)
optimizer = keras.optimizers.Adam(lr=0.005)
model.compile(loss='binary_crossentropy',
              optimizer=optimizer,
              metrics=['binary_accuracy'])

hist = model.fit(x_train, y_train, batch_size=batch_size, epochs=nb_epochs,
                  verbose=1, validation_data=(x_test, y_test))
```

With tf 2.4.1:
`InvalidArgumentError:  Only one input size may be -1, not both 0 and 2` when reshaping line 60 of _general_conv. If I modify this line 60 with `s1 = tf.reshape(s1, [self.bs, self.cn, s1.shape[-1], 1])` (line I changed before to make it work with db2), I got:
`InvalidArgumentError:  All dimensions except 2 must match. Input 1 has shape [20 819 0] and doesn't match input 0 with shape [10 819 4].`

With tf 1.14.0:
`ValueError: Shape must be rank 4 but is rank 5 for 'conv1d' (op: 'Conv2D') with input shapes: [?,1,0,?,1], [1,30,1,1].
` in line 65 of _general_conv: `rl = tf.nn.conv1d(s1, k1l, stride=2, padding='VALID')`

Do you have any insights? Thanks

**Comment by fversaci** [comment]
My bad: something I had fixed in the 2D case, but forgot to fix in 1D. I pushed a fix, now it should hopefully work.

**Comment by pmdnhd** [comment]
Thanks for the fix, unfortunately not yet. 
With tf 2.4.1:
in the first ConcatOp:
`InvalidArgumentError:  All dimensions except 2 must match. Input 1 has shape [20 819 0] and doesn't match input 0 with shape [10 819 4].` By printing the model summary used in the previous snippet, a 0 dimension appears in the wavelet layers. This error is also raised by using only 1 wavelet layer.

**Comment by fversaci** [comment]
I'm running your snippet with no errors in tf 2.4.0. I'll try and upgrade to 2.4.1 and see what happens.

**Comment by fversaci** [comment]
Upgraded to tf 2.4.1 and still runs smoothly. Are you sure you pip-installed the latest version?

**Comment by pmdnhd** [comment]
Yes sorry the snippet runs. What does not run is by changing which channels to keep in the wavelet decomposition. If I understood well, in the snippet, the following lines
```
        wave1 = db15.call(wave0[:, :, :chans])
        wave2 = db15.call(wave1[:, :, :chans])
        wave3 = db15.call(wave2[:, :, :chans])
        wave4 = db15.call(wave3[:, :, :chans])
```
enable to keep the low levels of the wavelet decomposition. Nevertheless, if I want the high levels of the decomposition, I just need to modify as follow (is that right?):
```
        wave1 = db15.call(wave0[:, :, chans:])
        wave2 = db15.call(wave1[:, :, chans:])
        wave3 = db15.call(wave2[:, :, chans:])
        wave4 = db15.call(wave3[:, :, chans:])  
```
With the last configuration by choosing the high levels, it throws the previous error with the concat layer.

**Comment by fversaci** [comment]
I see: in your example `wave0` is the input, and hence it only has 1 channel and you cannot access any high components for that variable.

What you want to do is probably:
```python
        wave0 = inputs
        wave1 = db15.call(wave0[:, :, :chans])
        wave2 = db15.call(wave1[:, :, chans:])
        wave3 = db15.call(wave2[:, :, chans:])
        wave4 = db15.call(wave3[:, :, chans:])
```

**Comment by pmdnhd** [comment]
Yes, sorry for this silly mistake... Thank you again for your time, your help and this toolbox!

**Comment by fversaci** [comment]
No problem, and you helped me find a bug as well ;)
