### ISSUE TITLE
I got ValueError when calling the layer

### ISSUE THREAD

**Issue by llmpass** [fversaci/WaveTF#5]
https://github.com/fversaci/WaveTF/blob/6e3f2b04334a0a51476ad316e6d97965ce009f4b/wavetf/_haar_conv.py#L167

ValueError: Shape must be rank 4 but is rank 5 for 'conv1d' (op: 'Conv2D') with input shapes: [1,1,768,256,1], [1,2,1,1].

With my code:

tf.reset_default_graph()
img = tf.placeholder(tf.float32, shape=(1, 256, 256, 3))
features = HaarWaveLayer2D().call(img)

Any ideas why?

**Comment by fversaci** [comment]
Hi, it seems you're using Tensorflow 1, which is not tested/supported.

I tried the following code with Tensorflow 2 and runs without errors:
```python
import tensorflow as tf
from wavetf._haar_conv import HaarWaveLayer2D

tf.compat.v1.disable_eager_execution()
img = tf.compat.v1.placeholder(tf.float32, shape=(1, 256, 256, 3))
features = HaarWaveLayer2D().call(img)
print(features.shape)
```
Also, are you using the latest version of WaveTF (v0.1.1 = current master)?

**Comment by llmpass** [comment]
> Hi, it seems you're using Tensorflow 1, which is not tested/supported.
> 
> I tried the following code with Tensorflow 2 and runs without errors:
> 
> ```python
> import tensorflow as tf
> from wavetf._haar_conv import HaarWaveLayer2D
> 
> tf.compat.v1.disable_eager_execution()
> img = tf.compat.v1.placeholder(tf.float32, shape=(1, 256, 256, 3))
> features = HaarWaveLayer2D().call(img)
> print(features.shape)
> ```
> 
> Also, are you using the latest version of WaveTF (v0.1.1 = current master)?

bad... I'm using tf1 :(

**Comment by llmpass** [comment]
Does this class work for 
img = tf.compat.v1.placeholder(tf.float32, shape=(None, None, None, 3)) ?

**Comment by fversaci** [comment]
No, you must provide at least the x and y (and channels) dimensions.
