### ISSUE TITLE
Error: Only one input size may be -1, not both 0 and 2

### ISSUE THREAD

**Issue by thupalo** [fversaci/WaveTF#6]
To avoid runtime error with tf.reshape
Error: Only one input size may be -1, not both 0 and 2
Please consider a small code change in:
_daubachies_conv.py line 216

```
        # s1 = tf.reshape(s1, [self.bs, self.cn*self.ox, -1, 1])            # >>> delete
        ny_dim = s1.shape[3]                                                # <<< insert
        s1 = tf.reshape(s1, [self.bs, self.cn*self.ox, ny_dim, 1])          # <<< insert

```

**Comment by fversaci** [comment]
Thanks, it does seem reasonable: for now I pushed it as commit c110461 in branch [develop](https://github.com/fversaci/WaveTF/tree/github/develop).
See if that works for you.
